# Generated by Django 3.2.5 on 2021-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='profilePic',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
